version: '3'

services:
  server:
    build: ./server
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - '8080:8080'
    volumes:
      - /app/node_modules
      - ./client:/app